#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Set GTK Themes, Icons, Cursor and Fonts

THEME='Arc-Dark'
ICONS='Qogir-Dark'
FONT='Noto Sans 10'
#FONT='Noto Naskh Arabic 10'
CURSOR='Qogir-Dark'
CURSORSIZE=24

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes () {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
  hyprctl setcursor "$CURSOR" $CURSORSIZE
	${SCHEMA} font-name "$FONT"
}

apply_themes
