#!/usr/bin/env bash

if command -v helium >/dev/null 2>&1; then
    helium
elif command -v google-chrome-stable >/dev/null 2>&1; then
    google-chrome-stable
elif command -v brave >/dev/null 2>&1; then
    brave
else
    # خيار احتياطي في حال عدم وجود أي مما سبق
    echo "لم يتم العثور على متصفح مدعوم. محاولة تشغيل المتصفح الافتراضي..."
    xdg-open "http://localhost:3000"
fi
